[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/.pnpm/**"]
  [functions."___netlify-server-handler"]
    included_files = ["!node_modules/.pnpm/**"]
    node_bundler = "esbuild"
    region = "aws-us-east-1" 