[build]
  command = "npm run build"
  publish = ".next"

[functions]
  # Déplacer la fonction vers Francfort pour réduire la latence et exclure les fichiers inutiles
  region = "eu-central-1"
  included_files = ["!node_modules/.pnpm/**"]
  [functions."___netlify-server-handler"]
    included_files = ["!node_modules/.pnpm/**"]
    node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs" 